
platform :ios, '7.0'
use_frameworks!

target 'RTRootNavigationController_Example' do
  pod 'RTRootNavigationController', :path => '../'

  target 'RTRootNavigationController_Tests' do
    
  end
end
